//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcNo_Transcoder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcNo_Transcoder.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # ----------------------------------------------------
        ///# Welcome to TechNobo&apos;s Video Transcoder settings
        ///# Created by TechNobo (Wesley Pyburn): https://tcno.co/
        ///# GitHub Repo: https://github.com/TcNobo/TcNo-Transcoder
        ///# ----------------------------------------------------
        ///
        ///
        ///# ----------------------------------------------------
        ///# --------------------- REQUIRED ---------------------
        ///# ----------------------------------------------------
        ///# Output format
        ///OutputFormat=mp4
        ///
        ///# Copy the audio?
        ///# Yes  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _LOCALISEDSETTINGS {
            get {
                return ResourceManager.GetString("_LOCALISEDSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------- INFORMATION ---------------------
        ///--&gt; Settings.cfg file was generated.
        ///--&gt; If this is your first time using this program, make sure to read the wiki:
        ///--&gt; https://github.com/TcNobo/TcNo-Transcoder/wiki
        ///--&gt; (You can delete the file to reset it at any stage)
        ///-------------------------------------------------------.
        /// </summary>
        internal static string ErrFailedSettingsFind {
            get {
                return ResourceManager.GetString("ErrFailedSettingsFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read settings file. Check everything is correct and try again.
        ///Error: {0}.
        /// </summary>
        internal static string ErrFailedSettingsRead {
            get {
                return ResourceManager.GetString("ErrFailedSettingsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Nvidia GPU was found. Try run as admin, update drivers or report this issue on GitHub, providing as much info as possible..
        /// </summary>
        internal static string ErrNoNV {
            get {
                return ResourceManager.GetString("ErrNoNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queue.exe appears to be empty. Please check the file contains a new file/folder on each new line, with no trailing spaces or extra characters. (A new line at the end of the file is intended).
        /// </summary>
        internal static string ErrQueueEmpty {
            get {
                return ResourceManager.GetString("ErrQueueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queue.txt not found or inaccessible in ./extra/ folder.
        /// </summary>
        internal static string ErrQueueNotFound {
            get {
                return ResourceManager.GetString("ErrQueueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0} was not found in the settings file, or there was another error involving it.
        ///Please verify the settings file and try again..
        /// </summary>
        internal static string ErrSettingNotFound {
            get {
                return ResourceManager.GetString("ErrSettingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped..
        /// </summary>
        internal static string ErrStopped {
            get {
                return ResourceManager.GetString("ErrStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}
        ///NvencC Version: {1}
        ///Min. Nvidia Driver Version: {2}
        ///
        ///GitHub: https://github.com/TcNobo/TcNo-Transcoder
        ///GitHub Wiki: https://github.com/TcNobo/TcNo-Transcoder/wiki
        ///YouTube: https://YouTube.com/TechNobo
        ///Web: https://tcno.co/.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;yes&quot; when asked if you want to run as admin.
        ///--&gt; Waiting for program completion....
        /// </summary>
        internal static string InfoAdminPrompt {
            get {
                return ResourceManager.GetString("InfoAdminPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TechNobo&apos;s Video Transcoder
        ///------------------------------------------
        ///FIRST: Audio ENCODERS and then DECODERS.
        ///
        ///To see a list of videdo encoders, use -v
        ///
        ///------------------------------------------
        ///Listing available audio ENCODERS (output)
        ///------------------------------------------
        ///
        ///#
        ///
        ///------------------------------------------
        ///Listing available audio DECODERS (input)
        ///------------------------------------------
        ///
        ///
        ///#
        ///
        ///------------------------------------------.
        /// </summary>
        internal static string InfoAudio {
            get {
                return ResourceManager.GetString("InfoAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything complete.
        ///---------------------
        ///Start time: {0}
        ///Finish time: {1}
        ///---------------------
        ///Thanks for using TechNobo&apos;s Transcoder!
        ///---------------------
        ///GitHub: https://github.com/TcNobo/TcNo-Transcoder
        ///YouTube: https://YouTube.com/TechNobo
        ///Web: https://tcno.co/.
        /// </summary>
        internal static string InfoComplete {
            get {
                return ResourceManager.GetString("InfoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything complete.
        ///---------------------
        ///Thanks for using TechNobo&apos;s Transcoder!
        ///---------------------
        ///GitHub: https://github.com/TcNobo/TcNo-Transcoder
        ///YouTube: https://YouTube.com/TechNobo
        ///Web: https://tcno.co/.
        /// </summary>
        internal static string InfoCompleteNoTime {
            get {
                return ResourceManager.GetString("InfoCompleteNoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --&gt; Finished!
        ///You should now see &quot;TcNo-Transcode&quot; in your context menu..
        /// </summary>
        internal static string InfoContextMenuComplete {
            get {
                return ResourceManager.GetString("InfoContextMenuComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE:
        ///When manually setting: use 0, 1, or any other integer, next to the GPU of your choice.
        /// 
        ///The following GPU&apos;s are available for NVEncC transcoding:.
        /// </summary>
        internal static string InfoDevices {
            get {
                return ResourceManager.GetString("InfoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        ///Welcome to TechNobo&apos;s Video Transcoder {0}
        ///built for generating Proxy files with multitrack audio quickly.
        ///
        ///---------------------------------------
        ///
        ///BASIC USAGE:
        ///Edit settings in settings.cfg.
        ///Either:
        ///    - Run this .exe without arguments and follow instructions on screen.
        ///    - Drag and drop a file/folder onto this .exe
        ///    - Right click a file/folder, &quot;Add to TcNo Transcode Queue&quot; and run this .exe (See &apos;Queue information&apos; below)
        ///
        ///---------------------------------------
        ///
        ///INFORMATION  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoHelp {
            get {
                return ResourceManager.GetString("InfoHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item complete.
        ///---------------------
        ///Start time: {0} | Finish time: {1}
        ///---------------------.
        /// </summary>
        internal static string InfoItemComplete {
            get {
                return ResourceManager.GetString("InfoItemComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------------
        ///Minimum Nvidia Driver requirements not met. This will likely cause issues, but the program will continue.
        ///--------------------------------------
        ///Installed Nvidia Driver: {0}
        ///Min. Driver required: {1}
        ///Consider updating before continuing.
        ///--------------------------------------.
        /// </summary>
        internal static string InfoNVDriverNotMet {
            get {
                return ResourceManager.GetString("InfoNVDriverNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything complete.
        ///---------------------
        ///Queue start time: {0}
        ///Queue finish time: {1}
        ///---------------------
        ///Thanks for using TechNobo&apos;s Transcoder!
        ///---------------------
        ///GitHub: https://github.com/TcNobo/TcNo-Transcoder
        ///YouTube: https://YouTube.com/TechNobo
        ///Web: https://tcno.co/.
        /// </summary>
        internal static string InfoQueueComplete {
            get {
                return ResourceManager.GetString("InfoQueueComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context menu is what pops up when you right-click anywhere.
        ///If you add TcNo-Transcoder to the Windows Context Menu using &quot;shell add&quot;, you can right-click:
        ///- Files and Folders to:
        ///    - ADD them to the queue.
        ///    - START the queue.
        ///- The background of a folder (The blank section, behind the files):
        ///    - START the queue.
        ///You can remove them at any time using &quot;shell remove&quot;
        ///
        ///USAGE: shell &lt;add/remove&gt;
        ///
        ///NOTE:
        ///Do not edit the file/folder structure of this program!
        ///If you move where the program f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoShell {
            get {
                return ResourceManager.GetString("InfoShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TechNobo&apos;s Video Transcoder
        ///------------------------------------------
        ///
        ///{0} --check - formats
        ///
        ///------------------------------------------
        ///Remember to scroll to the top.
        ///ABOVE: Video Muxers and Demuxers.
        ///
        ///    || D - : Demuxer(input) ONLY.
        ///    || -M : Muxer(output) ONLY
        ///    || DM : Demuxer and Muxer, both input and output available.
        ///
        ///To see a list of audio encoders, use -a
        ///------------------------------------------.
        /// </summary>
        internal static string InfoVideo {
            get {
                return ResourceManager.GetString("InfoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to TechNobo&apos;s Video Transcoder {0}
        ///------------------------
        ///Run with -h or --help to display help. (Or enter &quot;help&quot; below)
        ///Run with -i or --info to display info. (Or enter &quot;info&quot; below)
        ///To add/remove context menu option (Right clicking files) enter &quot;help shell&quot; below.
        ///------------------------.
        /// </summary>
        internal static string InfoWelcome {
            get {
                return ResourceManager.GetString("InfoWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS ANY KEY TO CLOSE....
        /// </summary>
        internal static string PrgAnyKeyToClose {
            get {
                return ResourceManager.GetString("PrgAnyKeyToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS ANY KEY TO CONTINUE....
        /// </summary>
        internal static string PrgAnyKeyToContinue {
            get {
                return ResourceManager.GetString("PrgAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using {0}
        ///The file will save to: {1}
        ///If you want it saved to a new directory, exit, and set it in settings.cfg.
        ///Press enter to continue....
        /// </summary>
        internal static string PrgChangeDir {
            get {
                return ResourceManager.GetString("PrgChangeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using {0}
        ///The files will save to their respective directories.
        ///Resolution: {1}
        ///FPS: {2}
        ///Codec: {3}
        ///If you want them saved to a new directory, or you want different settings: exit, and set theem in settings.cfg.
        ///Press enter to continue....
        /// </summary>
        internal static string PrgChangeDirQueue {
            get {
                return ResourceManager.GetString("PrgChangeDirQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to continue?.
        /// </summary>
        internal static string PrgContinue {
            get {
                return ResourceManager.GetString("PrgContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this correct? (y/n):.
        /// </summary>
        internal static string PrgCorrect {
            get {
                return ResourceManager.GetString("PrgCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION!
        ///Dragging files in will process them INSTANTLY using the settings in settings.cfg!
        ///
        ///The following files will be processed:.
        /// </summary>
        internal static string PrgDragDropNotice {
            get {
                return ResourceManager.GetString("PrgDragDropNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop input file/folder into here:.
        /// </summary>
        internal static string PrgDragDropPrompt {
            get {
                return ResourceManager.GetString("PrgDragDropPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files will be processed:.
        /// </summary>
        internal static string PrgFollowingFiles {
            get {
                return ResourceManager.GetString("PrgFollowingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now processing: {0}
        ///Saving to: {1}.
        /// </summary>
        internal static string PrgNowProcessing {
            get {
                return ResourceManager.GetString("PrgNowProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue processing cancelled..
        /// </summary>
        internal static string PrgProcessingCancelled {
            get {
                return ResourceManager.GetString("PrgProcessingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A queue is detected. Would you like to process it? (Y to process / ANY other key to skip):.
        /// </summary>
        internal static string PrgQueryQueue {
            get {
                return ResourceManager.GetString("PrgQueryQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a directory. The following will be processed:.
        /// </summary>
        internal static string PrgQueueFollowingFiles {
            get {
                return ResourceManager.GetString("PrgQueueFollowingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------------
        ///The following files will be processed
        ///--------------------------------------
        ///{0}
        ///--------------------------------------
        ///
        ///You can edit the queue in the TcNo-Transcoder/extra/queue.txt file.
        ///Do you want to process these files? (y/n):.
        /// </summary>
        internal static string PrgQueueList {
            get {
                return ResourceManager.GetString("PrgQueueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List may be long, you might want to scroll up..
        /// </summary>
        internal static string PrgScrollUp {
            get {
                return ResourceManager.GetString("PrgScrollUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will render with the current settings:
        ///Resolution: {1}
        ///FPS: {2}
        ///Codec: {3}
        ///
        ///This command will be processed:.
        /// </summary>
        internal static string PrgVerifyRenderSettings {
            get {
                return ResourceManager.GetString("PrgVerifyRenderSettings", resourceCulture);
            }
        }
    }
}
